/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import modelos.Boletos;
import modelos.Disponibilidad;

/**
 *
 * @author ciroa
 */
public class ReporteVentaBoletos extends javax.swing.JFrame {
    modelos.Rutas rutas;
    javax.swing.JFrame main;
    ArrayList<objects.Boleto> boletos=new ArrayList<>();
    String [] labelsTtbl =new String [] {
                "RUTA", "FECHA", "HORA", "IDENTIFICACION", "APELLIDOS", "NOMBRES", "EDAD", "VALOR", "ASIENTOS"
            };
    /**
     * Creates new form ReporteVentaBoletos
     */
    
    public ReporteVentaBoletos() {
        initComponents();
    }
    public ReporteVentaBoletos(Principal main) {
        initComponents();
        YourTableCellRenderer centerRenderer = new YourTableCellRenderer(null);
        centerRenderer.setHorizontalAlignment( SwingConstants.CENTER );
        
        this.rutas=main.rutas;
        this.main=main;
        setConfigs();
        tblResultado.setModel(new javax.swing.table.DefaultTableModel(new Object [][] {},labelsTtbl));
        tblResultado.setDefaultEditor(Object.class, null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                main.setVisible(true);
                main.toFront();
            }
        });
    }
    public void setHorarios(){
        String valRuta=(String)cmbRuta.getSelectedItem();
        ArrayList<objects.Abstract> list=this.rutas.getList();
        ArrayList<String> labels=new ArrayList<>();
        for(objects.Abstract ruta: list) {
            objects.Ruta aux=((objects.Ruta)ruta);
            String rutaFinal=/*aux.getCodigo()+": "+*/aux.getParadaInicial()+" - "+aux.getParadaFinal();
            Boolean add=true;
            if(valRuta.equals(rutaFinal)){
                for(String label: labels) {
                    if(label.equals(aux.getHora()))
                        add=false;
                }
                if(add) labels.add(aux.getHora());
            }
        }
        String[] modelArr = new String[labels.size()];
        modelArr = labels.toArray(modelArr);
        DefaultComboBoxModel model = new DefaultComboBoxModel(modelArr);
        cmbHora.setModel(model);
    }
    public void setConfigs(){
        ArrayList<objects.Abstract> list=this.rutas.getList();
        ArrayList<String> labels=new ArrayList<>();
        for(objects.Abstract ruta: list) {
            objects.Ruta aux=((objects.Ruta)ruta);
            String rutaFinal=/*aux.getCodigo()+": "+*/aux.getParadaInicial()+" - "+aux.getParadaFinal();
            System.out.println(rutaFinal);
            Boolean add=true;
            for(String label: labels) {
                if(label.equals(rutaFinal))
                    add=false;
            }
            if(add) labels.add(rutaFinal);
        }
        String[] modelArr = new String[labels.size()];
        modelArr = labels.toArray(modelArr);
        DefaultComboBoxModel model = new DefaultComboBoxModel(modelArr);
        cmbRuta.setModel(model);
        this.setHorarios();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbRuta = new javax.swing.JComboBox<>();
        cmbHora = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dtpFecha = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reporte de Venta de Boletos");
        jLabel1.setAutoscrolls(true);
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Consulta de Boletos vendidos");

        jLabel3.setText("Ruta");

        cmbRuta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UIO – LOJA", "LOJA – UIO" }));
        cmbRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRutaActionPerformed(evt);
            }
        });

        cmbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "05h45 y 15h00", "07h00 y 16h30" }));

        jLabel4.setText("Fecha");

        jLabel5.setText("Hora");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cmbRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dtpFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cmbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(dtpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        tblResultado.getTableHeader().setResizingAllowed(false);
        tblResultado.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblResultado);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Editar Venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Eliminar Asiento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void search(){
        Boletos dis=new Boletos();
        dis.readData();  
        String fecha=((JTextField)dtpFecha.getDateEditor().getUiComponent()).getText();
        if(!"".equals(fecha.trim())){           
            boletos=dis.Search(cmbRuta.getSelectedItem().toString(),cmbHora.getSelectedItem().toString(), ((JTextField)dtpFecha.getDateEditor().getUiComponent()).getText());
            if(boletos.size()>0){
                Object [][] tabla=new Object [boletos.size()][9];
                int i=0;
                for(objects.Boleto bol:boletos){
                    tabla[i]=new Object[]{ bol.getParadaInicial()+" - "+bol.getParadaFinal(), bol.getFecha(), bol.getHora(), bol.getIdentificacion(), bol.getApellidos(), bol.getNombres(), bol.getEdad(), bol.getValor(), bol.getAsiento() };
                    i++;
                }
                tblResultado.setModel(new javax.swing.table.DefaultTableModel(tabla,labelsTtbl));
            }else this.clearTable();
        } else this.clearTable();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.search();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row=tblResultado.getSelectedRow();
        if (row != -1){
            String ruta=tblResultado.getModel().getValueAt(row, 0).toString();
            String fecha=tblResultado.getModel().getValueAt(row, 1).toString();
            String hora=tblResultado.getModel().getValueAt(row, 2).toString();
            String iden=tblResultado.getModel().getValueAt(row, 3).toString();
            String[] num=tblResultado.getModel().getValueAt(row, 8).toString().split(":");
            
            Boletos dis=new Boletos();
            dis.readData();
            objects.Boleto bol=dis.SearchOne(ruta, hora, fecha, iden);
            if(bol!=null){
                //System.out.println(bol.getAsientosStr());
                String[] asientosStr=bol.getAsientosStr().split(";");
                if(asientosStr.length==1){
                    System.out.println("Eliminando Registro");
                    dis.deleteData(bol);
                }else{
                    String asientosNew="";
                    Double total=bol.getTotal();
                    for(int i=0;i<asientosStr.length;i++){
                         String[] asientoNum=asientosStr[i].split(":");
                         if(num[0].equals(asientoNum[0])){
                             total-=(Double.parseDouble(asientoNum[2]));
                         }else{
                             asientosNew+=(("".equals(asientosNew)?"":";")+asientosStr[i]);
                         }
                    }
                    
                    bol.setAsientosStr(asientosNew);
                    bol.setTotal(total);
                    System.out.println("Eliminando asiento Registro");
                    dis.updateData(bol);
                }
                modelos.Disponibilidad dispo=new Disponibilidad();
                dispo.readData();
                objects.Disponibilidad disponible=dispo.Search(ruta, hora, fecha);
                disponible.setOcupado(Integer.parseInt(num[0]), false);
                dispo.updateData(disponible);
                this.search();
            }else
                JOptionPane.showMessageDialog(null, "No se encontro el boleto a eliminar!", "InfoBox: " + "Alerta", JOptionPane.INFORMATION_MESSAGE);            
        }else
            JOptionPane.showMessageDialog(null, "Debe Seleccionar una el asiento a eliminar!", "InfoBox: " + "Alerta", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row=tblResultado.getSelectedRow();
        if (row != -1){
            String ruta=tblResultado.getModel().getValueAt(row, 0).toString();
            String fecha=tblResultado.getModel().getValueAt(row, 1).toString();
            String hora=tblResultado.getModel().getValueAt(row, 2).toString();
            String iden=tblResultado.getModel().getValueAt(row, 3).toString();
            String[] num=tblResultado.getModel().getValueAt(row, 8).toString().split(":");
            
            Boletos dis=new Boletos();
            dis.readData();
            objects.Boleto bol=dis.SearchOne(ruta, hora, fecha, iden);
            if(bol!=null){
                VentaBoleto cliente = new VentaBoleto((Principal)this.main,bol);
                cliente.setVisible(true);
                this.dispose();
            }else
                JOptionPane.showMessageDialog(null, "No se encontro el boleto a Editar!", "InfoBox: " + "Alerta", JOptionPane.INFORMATION_MESSAGE);            
        }else
            JOptionPane.showMessageDialog(null, "Debe Seleccionar una el asiento a Editar!", "InfoBox: " + "Alerta", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRutaActionPerformed
        this.setHorarios();
    }//GEN-LAST:event_cmbRutaActionPerformed
    private void clearTable(){
        boletos=new ArrayList<>();
        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                
            },labelsTtbl
        ));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteVentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteVentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteVentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteVentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteVentaBoletos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbHora;
    private javax.swing.JComboBox<String> cmbRuta;
    private com.toedter.calendar.JDateChooser dtpFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTable tblResultado;
    // End of variables declaration//GEN-END:variables
}
